### ISSUE TITLE
PANIC: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by billgraziano** [billgraziano/xelogstash#52]
```
goroutine 165 [running]:
github.com/billgraziano/xelogstash/app.(*Program).run.func1()
	C:/dev/github.com/xelogstash/app/program.go:165 +0x14f
panic(0xb9cb00, 0x128eef0)
	c:/go/src/runtime/panic.go:969 +0x174
github.com/billgraziano/xelogstash/logstash.(*Logstash).setTimeouts(0xc000222300)
	C:/dev/github.com/xelogstash/logstash/logstash.go:73 +0x4b
github.com/billgraziano/xelogstash/logstash.(*Logstash).Writeln(0xc000222300, 0xc002b5ec00, 0x5c7, 0xc000006648, 0x195)
	C:/dev/github.com/xelogstash/logstash/logstash.go:132 +0x15a
github.com/billgraziano/xelogstash/sink.(*LogstashSink).write(0xc00021f0b0, 0xc001b24d18, 0x5, 0xc002b5ec00, 0x5c7, 0x51b359, 0x12a0560, 0xc4dbc0)
	C:/dev/github.com/xelogstash/sink/logstash.go:185 +0x4e
github.com/billgraziano/xelogstash/sink.(*LogstashSink).Write(0xc00021f0b0, 0xd66380, 0xc0000e4340, 0xc001b24d18, 0x5, 0xc002b5ec00, 0x5c7, 0x0, 0x0, 0x0)
	C:/dev/github.com/xelogstash/sink/logstash.go:125 +0xbf
github.com/billgraziano/xelogstash/app.(*Program).processSession(0xc0001ba000, 0xd66380, 0xc0000e4340, 0xc, 0xc00246b380, 0xf, 0xc00246b378, 0x4, 0xc00246b3a0, 0xf, ...)
	C:/dev/github.com/xelogstash/app/process_session.go:300 +0x1b46
github.com/billgraziano/xelogstash/app.(*Program).ProcessSource(0xc0001ba000, 0xd66380, 0xc0000e4340, 0xc, 0xc00009d160, 0xf, 0xc0000d0780, 0x6, 0x6, 0x0, ...)
	C:/dev/github.com/xelogstash/app/process_source.go:64 +0xbb3
github.com/billgraziano/xelogstash/app.(*Program).run(0xc0001ba000, 0xd66380, 0xc0000e4340, 0xc, 0x0, 0x0, 0x0, 0x0, 0xc00009f000, 0x4, ...)
	C:/dev/github.com/xelogstash/app/program.go:214 +0x632
created by github.com/billgraziano/xelogstash/app.(*Program).startPolling
	C:/dev/github.com/xelogstash/app/program.go:138 +0xa3e

goroutine 1 [syscall, 28 minutes, locked to thread]:
syscall.Syscall(0x7ffa73f8f5f0, 0x1, 0xc0000c5c68, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/runtime/syscall_windows.go:188 +0xe9
golang.org/x/sys/windows.StartServiceCtrlDispatcher(0xc0000c5c68, 0xc88bc0, 0xc000049ac0)
	C:/Users/graz/go/pkg/mod/golang.org/x/sys@v0.0.0-20191210023423-ac6580df4449/windows/zsyscall_windows.go:508 +0x6b
golang.org/x/sys/windows/svc.Run(0xc62055, 0xb, 0xd5d0e0, 0xc00005d140, 0xd60e00, 0xc0001ba000)
	C:/Users/graz/go/pkg/mod/golang.org/x/sys@v0.0.0-20191210023423-ac6580df4449/windows/svc/service.go:352 +0x1be
github.com/kardianos/service.(*windowsService).Run(0xc00005d140, 0xc000000006, 0xc658e0)
	C:/Users/graz/go/pkg/mod/github.com/kardianos/service@v1.1.0/service_windows.go:261 +0x18a
main.main()
	C:/dev/github.com/xelogstash/cmd/sqlxewriter/main.go:146 +0xf4a

goroutine 21 [chan receive]:
github.com/billgraziano/xelogstash/app.ConfigureExpvar.func1()
	C:/dev/github.com/xelogstash/app/expvar.go:35 +0xc1
created by github.com/billgraziano/xelogstash/app.ConfigureExpvar
	C:/dev/github.com/xelogstash/app/expvar.go:34 +0x6e5

goroutine 20 [chan receive, 28 minutes]:
github.com/kardianos/service.(*windowsService).Execute(0xc00005d140, 0xc000084c50, 0x1, 0x1, 0xc000082120, 0xc000082180, 0x0)
	C:/Users/graz/go/pkg/mod/github.com/kardianos/service@v1.1.0/service_windows.go:175 +0x115
golang.org/x/sys/windows/svc.(*service).run.func1(0xc000049ac0, 0xc000084c50, 0x1, 0x1, 0xc000082120, 0xc000082180, 0xc0000821e0)
	C:/Users/graz/go/pkg/mod/golang.org/x/sys@v0.0.0-20191210023423-ac6580df4449/windows/svc/service.go:238 +0x71
created by golang.org/x/sys/windows/svc.(*service).run
	C:/Users/graz/go/pkg/mod/golang.org/x/sys@v0.0.0-20191210023423-ac6580df4449/windows/svc/service.go:237 +0x203

goroutine 6 [select, 28 minutes]:
golang.org/x/sys/windows/svc.(*service).run(0xc000049ac0)
	C:/Users/graz/go/pkg/mod/golang.org/x/sys@v0.0.0-20191210023423-ac6580df4449/windows/svc/service.go:250 +0x379
created by golang.org/x/sys/windows/svc.Run
	C:/Users/graz/go/pkg/mod/golang.org/x/sys@v0.0.0-20191210023423-ac6580df4449/windows/svc/service.go:350 +0x1b0

goroutine 152 [IO wait, 14040 minutes]:
internal/poll.runtime_pollWait(0x27930f08, 0x72, 0xd5e200)
	c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc000182948, 0x72, 0x1252500, 0x0, 0x0)
	c:/go
```

**Comment by billgraziano** [comment]
Consider just pretending that we got a config file change event and reloading everything.
